# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_by', models.CharField(max_length=250)),
                ('app_id', models.CharField(max_length=250)),
                ('app_name', models.CharField(max_length=250)),
                ('dev_name', models.CharField(max_length=250)),
                ('app_icon', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SearchStrings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchstring', models.CharField(max_length=250)),
                ('searched_time', models.DateTimeField(auto_now=True)),
                ('amount_of_time_searched', models.CharField(max_length=100)),
            ],
        ),
    ]
