# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Results',
            new_name='Result',
        ),
        migrations.RenameModel(
            old_name='SearchStrings',
            new_name='SearchString',
        ),
    ]
