# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 20:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171011_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='searched_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SearchString'),
        ),
        migrations.AlterField(
            model_name='searchstring',
            name='searched_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 11, 1, 32, 54, 689624)),
        ),
    ]
